

export const memory: WebAssembly.Memory;
export const __wbg_ajisaiinterpreter_free: (a: number, b: number) => void;
export const ajisaiinterpreter_clear_io_output_buffer: (a: number) => void;
export const ajisaiinterpreter_execute: (a: number, b: number, c: number) => any;
export const ajisaiinterpreter_execute_step: (a: number, b: number, c: number) => any;
export const ajisaiinterpreter_get_builtin_words_info: (a: number) => any;
export const ajisaiinterpreter_get_custom_words_info: (a: number) => any;
export const ajisaiinterpreter_get_imported_modules: (a: number) => any;
export const ajisaiinterpreter_get_io_output_buffer: (a: number) => [number, number];
export const ajisaiinterpreter_get_module_words_info: (a: number, b: number, c: number) => any;
export const ajisaiinterpreter_get_stack: (a: number) => any;
export const ajisaiinterpreter_get_word_definition: (a: number, b: number, c: number) => any;
export const ajisaiinterpreter_new: () => number;
export const ajisaiinterpreter_push_json_string: (a: number, b: number, c: number) => [number, number, number];
export const ajisaiinterpreter_remove_word: (a: number, b: number, c: number) => void;
export const ajisaiinterpreter_reset: (a: number) => any;
export const ajisaiinterpreter_restore_custom_words: (a: number, b: any) => [number, number];
export const ajisaiinterpreter_restore_imported_modules: (a: number, b: any) => void;
export const ajisaiinterpreter_restore_stack: (a: number, b: any) => [number, number];
export const ajisaiinterpreter_set_input_buffer: (a: number, b: number, c: number) => void;
export const wasm_bindgen__closure__destroy__h881c6ff590a92e5d: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hf49e72bbb773a9bc: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h1a9b24889a5b283c: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h3a5ef20a20cefb4e: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__he32a8c35689af319: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
