//! The Semantic Plane.
//!
//! A value carries two planes. The Data Plane is what the value *is*: a
//! number, a vector, a truth value, an absence. The Semantic Plane is how the
//! value is *read*: the same vector of three numbers is a raw triple, or a
//! piece of text, or nothing else — because those are the only readings
//! Ajisai defines.
//!
//! The Semantic Plane has exactly one canonical home: the [`role`] field of
//! [`Value`](crate::value::Value). The stack does not keep a parallel array of
//! roles, the interpreter does not keep a registry of roles, and nothing
//! anywhere has to be kept in sync with anything else. A role travels with its
//! value, including into and out of vectors, quotes, and the dictionary.
//!
//! Roles never change arithmetic, comparison, logic, or equality. They change
//! rendering, they are observable through `ROLE`, and `>INTERVAL` checks that
//! the reading it asserts is actually well formed. That is the whole of their
//! effect, and the specification says so rather than claiming a purity the
//! implementation does not have.
//!
//! Water: the Data Plane is the water; the Semantic Plane is what we have
//! decided to read off the gauge.

use std::fmt;

use crate::value::{Value, ValueData};

/// A value's reading on the Semantic Plane.
///
/// Every variant is generated by a named path, consumed by the renderer and by
/// `ROLE`, and carried by a stated propagation rule. There are no variants
/// reserved for future use.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub enum Role {
    /// No particular reading. Generated by every numeric and vector literal,
    /// by every computed result, and by `>RAW`.
    #[default]
    Raw,
    /// A vector of Unicode scalar values read as text. Generated by text
    /// literals and by `>TEXT`; rendered as `"..."`.
    Text,
    /// A two-element vector `[ lo hi ]` with `lo <= hi`, read as the closed
    /// interval from `lo` to `hi`. Generated by `>INTERVAL`; rendered as
    /// `lo..hi`.
    Interval,
}

impl Role {
    /// The name `ROLE` pushes, and the name accepted in documentation.
    pub fn name(self) -> &'static str {
        match self {
            Role::Raw => "RAW",
            Role::Text => "TEXT",
            Role::Interval => "INTERVAL",
        }
    }

    /// Every role, for the manifest and for exhaustiveness tests.
    pub const ALL: [Role; 3] = [Role::Raw, Role::Text, Role::Interval];

    /// The reading two values agree on, used when an operation joins
    /// containers (`CONCAT`, `APPEND`). Disagreement collapses to `Raw`
    /// rather than silently preferring one side.
    pub fn join(self, other: Role) -> Role {
        if self == other {
            self
        } else {
            Role::Raw
        }
    }
}

impl fmt::Display for Role {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.name())
    }
}

/// Whether `value` is shaped so that `role` is a well-formed reading of it.
///
/// This is the *only* definition of role well-formedness in the language. The
/// asserting words (`>TEXT`, `>INTERVAL`) call it and raise
/// [`Error::BadRole`](crate::error::Error::BadRole) on failure; the
/// propagating words call [`retain`] and fall back to [`Role::Raw`]. One rule,
/// two ways of reacting to it — so a role can never survive onto a value whose
/// shape contradicts it.
pub fn admits(role: Role, value: &Value) -> std::result::Result<(), String> {
    match role {
        Role::Raw => Ok(()),
        Role::Text => match value.data() {
            ValueData::Vector(items) => {
                for item in items.iter() {
                    let ok = match item.data() {
                        ValueData::Number(n) => n.as_codepoint().is_some(),
                        _ => false,
                    };
                    if !ok {
                        return Err(format!(
                            "every element must be a Unicode scalar value; found {}",
                            item.type_name()
                        ));
                    }
                }
                Ok(())
            }
            other => Err(format!("expected a vector, got {}", type_name(other))),
        },
        Role::Interval => match value.data() {
            ValueData::Vector(items) if items.len() == 2 => {
                match (items[0].as_number(), items[1].as_number()) {
                    (Some(lo), Some(hi)) if lo <= hi => Ok(()),
                    (Some(_), Some(_)) => {
                        Err("the low bound must not exceed the high bound".to_string())
                    }
                    _ => Err("both bounds must be numbers".to_string()),
                }
            }
            ValueData::Vector(items) => Err(format!(
                "expected a vector of exactly 2 bounds, got {}",
                items.len()
            )),
            other => Err(format!("expected a vector, got {}", type_name(other))),
        },
    }
}

/// Carry `role` onto `value` if the shape still admits it, and drop to
/// [`Role::Raw`] if it does not.
pub fn retain(role: Role, value: &Value) -> Role {
    if admits(role, value).is_ok() {
        role
    } else {
        Role::Raw
    }
}

fn type_name(data: &ValueData) -> &'static str {
    match data {
        ValueData::Boolean(_) => "boolean",
        ValueData::Unknown => "UNKNOWN",
        ValueData::Nil => "NIL",
        ValueData::Number(_) => "number",
        ValueData::Vector(_) => "vector",
        ValueData::Quote(_) => "quote",
    }
}
