//! Ajisai Core's vocabulary.
//!
//! This table is the whole of it. There is one registry, one contract per
//! word, and no classification axis beside it: no stability tier, no
//! exploratory bucket, no portability profile, no per-word optimizer hint. A
//! word is in Ajisai Core or it is in a package.

pub mod arith;
pub mod compare;
pub mod dict;
pub mod hof;
pub mod logic;
pub mod plane;
pub mod stack;
pub mod support;
pub mod vector;

use crate::contract::{Arity, Body, Policy, StakSupport, TypeSpec, Word, WordContract};
use crate::role::Role;

const CORE: &str = "ajisai-core";

const fn word(contract: WordContract, body: Body) -> Word {
    Word {
        contract,
        body,
        package: CORE,
    }
}

const fn fixed(inn: u8, out: u8) -> Arity {
    Arity::Fixed { inn, out }
}

use TypeSpec::{Any, Boolean, Number, Quote, Text, TruthValue, Vector};

/// Build the Ajisai Core vocabulary.
pub fn core_words() -> Vec<Word> {
    vec![
        // ------------------------------------------------------- constants
        word(
            WordContract {
                name: "TRUE",
                stack_effect: "( -- truth )",
                arity: fixed(0, 1),
                input_types: &[],
                output_types: &[Boolean],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::INERT,
                stak: StakSupport::Unsupported,
                role_required: None,
                summary: "The settled truth value TRUE.",
            },
            Body::Op(logic::constant_true),
        ),
        word(
            WordContract {
                name: "FALSE",
                stack_effect: "( -- truth )",
                arity: fixed(0, 1),
                input_types: &[],
                output_types: &[Boolean],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::INERT,
                stak: StakSupport::Unsupported,
                role_required: None,
                summary: "The settled truth value FALSE.",
            },
            Body::Op(logic::constant_false),
        ),
        word(
            WordContract {
                name: "UNKNOWN",
                stack_effect: "( -- truth )",
                arity: fixed(0, 1),
                input_types: &[],
                output_types: &[TruthValue],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::CARRIES,
                stak: StakSupport::Unsupported,
                role_required: None,
                summary: "The third truth value: observed, and still unsettled.",
            },
            Body::Op(logic::constant_unknown),
        ),
        word(
            WordContract {
                name: "NIL",
                stack_effect: "( -- nil )",
                arity: fixed(0, 1),
                input_types: &[],
                output_types: &[Any],
                nil_policy: Policy::CARRIES,
                unknown_policy: Policy::INERT,
                stak: StakSupport::Unsupported,
                role_required: None,
                summary: "The flow that carries no value.",
            },
            Body::Op(logic::constant_nil),
        ),
        // ------------------------------------------------------ arithmetic
        word(
            WordContract {
                name: "ADD",
                stack_effect: "( a b -- sum )",
                arity: fixed(2, 1),
                input_types: &[Number, Number],
                output_types: &[Number],
                nil_policy: Policy::CARRIES,
                unknown_policy: Policy::CARRIES,
                stak: StakSupport::FoldLeft,
                role_required: None,
                summary: "Exact sum.",
            },
            Body::Op(arith::add),
        ),
        word(
            WordContract {
                name: "SUB",
                stack_effect: "( a b -- difference )",
                arity: fixed(2, 1),
                input_types: &[Number, Number],
                output_types: &[Number],
                nil_policy: Policy::CARRIES,
                unknown_policy: Policy::CARRIES,
                stak: StakSupport::FoldLeft,
                role_required: None,
                summary: "Exact difference, a minus b.",
            },
            Body::Op(arith::sub),
        ),
        word(
            WordContract {
                name: "MUL",
                stack_effect: "( a b -- product )",
                arity: fixed(2, 1),
                input_types: &[Number, Number],
                output_types: &[Number],
                nil_policy: Policy::CARRIES,
                unknown_policy: Policy::CARRIES,
                stak: StakSupport::FoldLeft,
                role_required: None,
                summary: "Exact product.",
            },
            Body::Op(arith::mul),
        ),
        word(
            WordContract {
                name: "DIV",
                stack_effect: "( a b -- quotient )",
                arity: fixed(2, 1),
                input_types: &[Number, Number],
                output_types: &[Number],
                nil_policy: Policy::CARRIES,
                unknown_policy: Policy::CARRIES,
                stak: StakSupport::FoldLeft,
                role_required: None,
                summary: "Exact quotient. Division by zero is an error, not an infinity.",
            },
            Body::Op(arith::div),
        ),
        word(
            WordContract {
                name: "MIN",
                stack_effect: "( a b -- lesser )",
                arity: fixed(2, 1),
                input_types: &[Number, Number],
                output_types: &[Number],
                nil_policy: Policy::CARRIES,
                unknown_policy: Policy::CARRIES,
                stak: StakSupport::FoldLeft,
                role_required: None,
                summary: "The lesser of two numbers.",
            },
            Body::Op(arith::min),
        ),
        word(
            WordContract {
                name: "MAX",
                stack_effect: "( a b -- greater )",
                arity: fixed(2, 1),
                input_types: &[Number, Number],
                output_types: &[Number],
                nil_policy: Policy::CARRIES,
                unknown_policy: Policy::CARRIES,
                stak: StakSupport::FoldLeft,
                role_required: None,
                summary: "The greater of two numbers.",
            },
            Body::Op(arith::max),
        ),
        word(
            WordContract {
                name: "NEG",
                stack_effect: "( a -- negated )",
                arity: fixed(1, 1),
                input_types: &[Number],
                output_types: &[Number],
                nil_policy: Policy::CARRIES,
                unknown_policy: Policy::CARRIES,
                stak: StakSupport::MapEach,
                role_required: None,
                summary: "Negation.",
            },
            Body::Op(arith::neg),
        ),
        word(
            WordContract {
                name: "ABS",
                stack_effect: "( a -- magnitude )",
                arity: fixed(1, 1),
                input_types: &[Number],
                output_types: &[Number],
                nil_policy: Policy::CARRIES,
                unknown_policy: Policy::CARRIES,
                stak: StakSupport::MapEach,
                role_required: None,
                summary: "Magnitude.",
            },
            Body::Op(arith::abs),
        ),
        // ------------------------------------------------------ comparison
        word(
            WordContract {
                name: "EQ",
                stack_effect: "( a b -- truth )",
                arity: fixed(2, 1),
                input_types: &[Any, Any],
                output_types: &[TruthValue],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::CARRIES,
                stak: StakSupport::Unsupported,
                role_required: None,
                summary: "Data Plane equality. NIL or UNKNOWN either side gives UNKNOWN.",
            },
            Body::Op(compare::eq),
        ),
        word(
            WordContract {
                name: "NE",
                stack_effect: "( a b -- truth )",
                arity: fixed(2, 1),
                input_types: &[Any, Any],
                output_types: &[TruthValue],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::CARRIES,
                stak: StakSupport::Unsupported,
                role_required: None,
                summary: "Data Plane inequality. NIL or UNKNOWN either side gives UNKNOWN.",
            },
            Body::Op(compare::ne),
        ),
        word(
            WordContract {
                name: "LT",
                stack_effect: "( a b -- truth )",
                arity: fixed(2, 1),
                input_types: &[Number, Number],
                output_types: &[TruthValue],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::CARRIES,
                stak: StakSupport::Unsupported,
                role_required: None,
                summary: "Strictly less than.",
            },
            Body::Op(compare::lt),
        ),
        word(
            WordContract {
                name: "LE",
                stack_effect: "( a b -- truth )",
                arity: fixed(2, 1),
                input_types: &[Number, Number],
                output_types: &[TruthValue],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::CARRIES,
                stak: StakSupport::Unsupported,
                role_required: None,
                summary: "Less than or equal.",
            },
            Body::Op(compare::le),
        ),
        word(
            WordContract {
                name: "GT",
                stack_effect: "( a b -- truth )",
                arity: fixed(2, 1),
                input_types: &[Number, Number],
                output_types: &[TruthValue],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::CARRIES,
                stak: StakSupport::Unsupported,
                role_required: None,
                summary: "Strictly greater than.",
            },
            Body::Op(compare::gt),
        ),
        word(
            WordContract {
                name: "GE",
                stack_effect: "( a b -- truth )",
                arity: fixed(2, 1),
                input_types: &[Number, Number],
                output_types: &[TruthValue],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::CARRIES,
                stak: StakSupport::Unsupported,
                role_required: None,
                summary: "Greater than or equal.",
            },
            Body::Op(compare::ge),
        ),
        // ----------------------------------------------------------- logic
        word(
            WordContract {
                name: "NOT",
                stack_effect: "( a -- truth )",
                arity: fixed(1, 1),
                input_types: &[TruthValue],
                output_types: &[TruthValue],
                nil_policy: Policy::REFUSES,
                unknown_policy: Policy::CARRIES,
                stak: StakSupport::MapEach,
                role_required: None,
                summary: "Strong Kleene negation.",
            },
            Body::Op(logic::not),
        ),
        word(
            WordContract {
                name: "AND",
                stack_effect: "( a b -- truth )",
                arity: fixed(2, 1),
                input_types: &[TruthValue, TruthValue],
                output_types: &[TruthValue],
                nil_policy: Policy::REFUSES,
                unknown_policy: Policy::CARRIES,
                stak: StakSupport::FoldLeft,
                role_required: None,
                summary: "Strong Kleene conjunction.",
            },
            Body::Op(logic::and),
        ),
        word(
            WordContract {
                name: "OR",
                stack_effect: "( a b -- truth )",
                arity: fixed(2, 1),
                input_types: &[TruthValue, TruthValue],
                output_types: &[TruthValue],
                nil_policy: Policy::REFUSES,
                unknown_policy: Policy::CARRIES,
                stak: StakSupport::FoldLeft,
                role_required: None,
                summary: "Strong Kleene disjunction.",
            },
            Body::Op(logic::or),
        ),
        // ------------------------------------------------------ predicates
        word(
            WordContract {
                name: "NIL?",
                stack_effect: "( a -- truth )",
                arity: fixed(1, 1),
                input_types: &[Any],
                output_types: &[Boolean],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::INERT,
                stak: StakSupport::MapEach,
                role_required: None,
                summary: "Whether the value is NIL. Always settles.",
            },
            Body::Op(logic::is_nil),
        ),
        word(
            WordContract {
                name: "UNKNOWN?",
                stack_effect: "( a -- truth )",
                arity: fixed(1, 1),
                input_types: &[Any],
                output_types: &[Boolean],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::INERT,
                stak: StakSupport::MapEach,
                role_required: None,
                summary: "Whether the value is UNKNOWN. Always settles.",
            },
            Body::Op(logic::is_unknown),
        ),
        word(
            WordContract {
                name: "NUMBER?",
                stack_effect: "( a -- truth )",
                arity: fixed(1, 1),
                input_types: &[Any],
                output_types: &[Boolean],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::INERT,
                stak: StakSupport::MapEach,
                role_required: None,
                summary: "Whether the value is a number.",
            },
            Body::Op(logic::is_number),
        ),
        word(
            WordContract {
                name: "VECTOR?",
                stack_effect: "( a -- truth )",
                arity: fixed(1, 1),
                input_types: &[Any],
                output_types: &[Boolean],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::INERT,
                stak: StakSupport::MapEach,
                role_required: None,
                summary: "Whether the value is a vector.",
            },
            Body::Op(logic::is_vector),
        ),
        word(
            WordContract {
                name: "BOOLEAN?",
                stack_effect: "( a -- truth )",
                arity: fixed(1, 1),
                input_types: &[Any],
                output_types: &[Boolean],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::INERT,
                stak: StakSupport::MapEach,
                role_required: None,
                summary: "Whether the value is TRUE or FALSE. UNKNOWN is not.",
            },
            Body::Op(logic::is_boolean),
        ),
        word(
            WordContract {
                name: "QUOTE?",
                stack_effect: "( a -- truth )",
                arity: fixed(1, 1),
                input_types: &[Any],
                output_types: &[Boolean],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::INERT,
                stak: StakSupport::MapEach,
                role_required: None,
                summary: "Whether the value is a quote.",
            },
            Body::Op(logic::is_quote),
        ),
        // ----------------------------------------------------- flow shaping
        word(
            WordContract {
                name: "DUP",
                stack_effect: "( a -- a a )",
                arity: fixed(1, 2),
                input_types: &[Any],
                output_types: &[Any, Any],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::INERT,
                stak: StakSupport::MapEach,
                role_required: None,
                summary: "Split the surface value in two, role included.",
            },
            Body::Op(stack::dup),
        ),
        word(
            WordContract {
                name: "DROP",
                stack_effect: "( a -- )",
                arity: fixed(1, 0),
                input_types: &[Any],
                output_types: &[],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::INERT,
                stak: StakSupport::MapEach,
                role_required: None,
                summary: "Let the surface value go.",
            },
            Body::Op(stack::drop),
        ),
        word(
            WordContract {
                name: "SWAP",
                stack_effect: "( a b -- b a )",
                arity: fixed(2, 2),
                input_types: &[Any, Any],
                output_types: &[Any, Any],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::INERT,
                stak: StakSupport::Unsupported,
                role_required: None,
                summary: "Exchange the two surface values.",
            },
            Body::Op(stack::swap),
        ),
        word(
            WordContract {
                name: "DEPTH",
                stack_effect: "( -- count )",
                arity: fixed(0, 1),
                input_types: &[],
                output_types: &[Number],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::INERT,
                stak: StakSupport::Unsupported,
                role_required: None,
                summary: "How many values are standing in the flow.",
            },
            Body::Full(hof::depth),
        ),
        // --------------------------------------------------------- vectors
        word(
            WordContract {
                name: "LENGTH",
                stack_effect: "( vector -- count )",
                arity: fixed(1, 1),
                input_types: &[Vector],
                output_types: &[Number],
                nil_policy: Policy::REFUSES,
                unknown_policy: Policy::REFUSES,
                stak: StakSupport::MapEach,
                role_required: None,
                summary: "How many elements the vector holds.",
            },
            Body::Op(vector::length),
        ),
        word(
            WordContract {
                name: "NTH",
                stack_effect: "( vector index -- element )",
                arity: fixed(2, 1),
                input_types: &[Vector, Number],
                output_types: &[Any],
                nil_policy: Policy::REFUSES,
                unknown_policy: Policy::REFUSES,
                stak: StakSupport::Unsupported,
                role_required: None,
                summary: "The element at a zero-based index, with its own role.",
            },
            Body::Op(vector::nth),
        ),
        word(
            WordContract {
                name: "FIRST",
                stack_effect: "( vector -- element )",
                arity: fixed(1, 1),
                input_types: &[Vector],
                output_types: &[Any],
                nil_policy: Policy::CARRIES,
                unknown_policy: Policy::REFUSES,
                stak: StakSupport::MapEach,
                role_required: None,
                summary: "The first element, or NIL when the vector is empty.",
            },
            Body::Op(vector::first),
        ),
        word(
            WordContract {
                name: "REST",
                stack_effect: "( vector -- vector )",
                arity: fixed(1, 1),
                input_types: &[Vector],
                output_types: &[Vector],
                nil_policy: Policy::REFUSES,
                unknown_policy: Policy::REFUSES,
                stak: StakSupport::MapEach,
                role_required: None,
                summary: "Everything after the first element.",
            },
            Body::Op(vector::rest),
        ),
        word(
            WordContract {
                name: "APPEND",
                stack_effect: "( vector value -- vector )",
                arity: fixed(2, 1),
                input_types: &[Vector, Any],
                output_types: &[Vector],
                nil_policy: Policy::REFUSES,
                unknown_policy: Policy::REFUSES,
                stak: StakSupport::Unsupported,
                role_required: None,
                summary: "The vector with one more element at the end.",
            },
            Body::Op(vector::append),
        ),
        word(
            WordContract {
                name: "CONCAT",
                stack_effect: "( vector vector -- vector )",
                arity: fixed(2, 1),
                input_types: &[Vector, Vector],
                output_types: &[Vector],
                nil_policy: Policy::REFUSES,
                unknown_policy: Policy::REFUSES,
                stak: StakSupport::FoldLeft,
                role_required: None,
                summary: "Two vectors run together.",
            },
            Body::Op(vector::concat),
        ),
        word(
            WordContract {
                name: "REVERSE",
                stack_effect: "( vector -- vector )",
                arity: fixed(1, 1),
                input_types: &[Vector],
                output_types: &[Vector],
                nil_policy: Policy::REFUSES,
                unknown_policy: Policy::REFUSES,
                stak: StakSupport::MapEach,
                role_required: None,
                summary: "The vector, back to front.",
            },
            Body::Op(vector::reverse),
        ),
        word(
            WordContract {
                name: "RANGE",
                stack_effect: "( from to -- vector )",
                arity: fixed(2, 1),
                input_types: &[Number, Number],
                output_types: &[Vector],
                nil_policy: Policy::REFUSES,
                unknown_policy: Policy::REFUSES,
                stak: StakSupport::Unsupported,
                role_required: None,
                summary: "The integers from `from` up to but not including `to`.",
            },
            Body::Op(vector::range),
        ),
        // ------------------------------------------------ words over quotes
        word(
            WordContract {
                name: "MAP",
                stack_effect: "( vector quote -- vector )",
                arity: fixed(2, 1),
                input_types: &[Vector, Quote],
                output_types: &[Vector],
                nil_policy: Policy::REFUSES,
                unknown_policy: Policy::REFUSES,
                stak: StakSupport::Unsupported,
                role_required: None,
                summary: "Run the quote on every element, in a basin seeded with that element.",
            },
            Body::Full(hof::map),
        ),
        word(
            WordContract {
                name: "FILTER",
                stack_effect: "( vector quote -- vector )",
                arity: fixed(2, 1),
                input_types: &[Vector, Quote],
                output_types: &[Vector],
                nil_policy: Policy::REFUSES,
                unknown_policy: Policy::REFUSES,
                stak: StakSupport::Unsupported,
                role_required: None,
                summary: "Keep the elements the quote calls TRUE. An UNKNOWN verdict is an error.",
            },
            Body::Full(hof::filter),
        ),
        word(
            WordContract {
                name: "FOLD",
                stack_effect: "( vector seed quote -- value )",
                arity: fixed(3, 1),
                input_types: &[Vector, Any, Quote],
                output_types: &[Any],
                nil_policy: Policy::REFUSES,
                unknown_policy: Policy::REFUSES,
                stak: StakSupport::Unsupported,
                role_required: None,
                summary: "Run the quote over accumulator and element, left to right.",
            },
            Body::Full(hof::fold),
        ),
        word(
            WordContract {
                name: "EXEC",
                stack_effect: "( quote -- ... )",
                arity: Arity::Dynamic,
                input_types: &[Quote],
                output_types: &[],
                nil_policy: Policy::REFUSES,
                unknown_policy: Policy::REFUSES,
                stak: StakSupport::Unsupported,
                role_required: None,
                summary: "Run the quote against the current flow.",
            },
            Body::Full(hof::exec),
        ),
        // -------------------------------------------------- semantic plane
        word(
            WordContract {
                name: ">TEXT",
                stack_effect: "( vector -- text )",
                arity: fixed(1, 1),
                input_types: &[Vector],
                output_types: &[Text],
                nil_policy: Policy::REFUSES,
                unknown_policy: Policy::REFUSES,
                stak: StakSupport::MapEach,
                role_required: None,
                summary: "Read a vector of codepoints as text. Checked, not asserted.",
            },
            Body::Op(plane::to_text),
        ),
        word(
            WordContract {
                name: ">INTERVAL",
                stack_effect: "( vector -- interval )",
                arity: fixed(1, 1),
                input_types: &[Vector],
                output_types: &[Vector],
                nil_policy: Policy::REFUSES,
                unknown_policy: Policy::REFUSES,
                stak: StakSupport::MapEach,
                role_required: None,
                summary: "Read a two-element vector as a closed interval. Checked, not asserted.",
            },
            Body::Op(plane::to_interval),
        ),
        word(
            WordContract {
                name: ">RAW",
                stack_effect: "( value -- value )",
                arity: fixed(1, 1),
                input_types: &[Any],
                output_types: &[Any],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::INERT,
                stak: StakSupport::MapEach,
                role_required: None,
                summary: "Forget the value's reading; the data is untouched.",
            },
            Body::Op(plane::to_raw),
        ),
        word(
            WordContract {
                name: "ROLE",
                stack_effect: "( value -- text )",
                arity: fixed(1, 1),
                input_types: &[Any],
                output_types: &[Text],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::INERT,
                stak: StakSupport::MapEach,
                role_required: None,
                summary: "The value's reading, as text. Pair with KEEP to observe without eating.",
            },
            Body::Op(plane::role_of),
        ),
        // ------------------------------------------------------ dictionary
        word(
            WordContract {
                name: "DEF",
                stack_effect: "( quote name -- )",
                arity: fixed(2, 0),
                input_types: &[Quote, Text],
                output_types: &[],
                nil_policy: Policy::REFUSES,
                unknown_policy: Policy::REFUSES,
                stak: StakSupport::Unsupported,
                role_required: Some((1, Role::Text)),
                summary: "Bind a quote to a name. Built-in and package words cannot be redefined.",
            },
            Body::Full(dict::def),
        ),
        word(
            WordContract {
                name: "DEL",
                stack_effect: "( name -- )",
                arity: fixed(1, 0),
                input_types: &[Text],
                output_types: &[],
                nil_policy: Policy::REFUSES,
                unknown_policy: Policy::REFUSES,
                stak: StakSupport::Unsupported,
                role_required: Some((0, Role::Text)),
                summary: "Remove a user definition.",
            },
            Body::Full(dict::del),
        ),
        // ------------------------------------------------------- directives
        word(
            WordContract {
                name: "TOP",
                stack_effect: "( -- )",
                arity: fixed(0, 0),
                input_types: &[],
                output_types: &[],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::INERT,
                stak: StakSupport::Unsupported,
                role_required: None,
                summary: "Draw the next word's operands from the surface. The default.",
            },
            Body::Directive,
        ),
        word(
            WordContract {
                name: "STAK",
                stack_effect: "( -- )",
                arity: fixed(0, 0),
                input_types: &[],
                output_types: &[],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::INERT,
                stak: StakSupport::Unsupported,
                role_required: None,
                summary: "Draw the next word's operands from the whole standing flow.",
            },
            Body::Directive,
        ),
        word(
            WordContract {
                name: "EAT",
                stack_effect: "( -- )",
                arity: fixed(0, 0),
                input_types: &[],
                output_types: &[],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::INERT,
                stak: StakSupport::Unsupported,
                role_required: None,
                summary: "The next word consumes what it drew. The default.",
            },
            Body::Directive,
        ),
        word(
            WordContract {
                name: "KEEP",
                stack_effect: "( -- )",
                arity: fixed(0, 0),
                input_types: &[],
                output_types: &[],
                nil_policy: Policy::INERT,
                unknown_policy: Policy::INERT,
                stak: StakSupport::Unsupported,
                role_required: None,
                summary: "The next word leaves what it drew standing, and branches above it.",
            },
            Body::Directive,
        ),
        word(
            WordContract {
                name: "VENT",
                stack_effect: "( truth -- )",
                arity: fixed(1, 0),
                input_types: &[TruthValue],
                output_types: &[],
                nil_policy: Policy::REFUSES,
                unknown_policy: Policy::CARRIES,
                stak: StakSupport::Unsupported,
                role_required: None,
                summary: "Release the next source unit if the gate is TRUE; block it otherwise.",
            },
            Body::Directive,
        ),
    ]
}
