// Packaged WASM backend: runs the one-shot WASM agent entry point
// (`rust/src/wasm_interpreter_bindings/wasm_agent.rs`) inside a
// worker_threads Worker, one Worker per call — the same one-shot-per-call
// isolation the native backend gets from spawning a subprocess per call.
// Never runs WASM synchronously on the stdio server's main thread, and the
// Worker is terminated the moment the existing hard wall-time limit elapses.
//
// Self-contained: the WASM module ships inside the npm package
// (`wasm/generated/`, regenerated by `../../scripts/rebuild-mcp-wasm.sh`), so
// this backend needs neither `AJISAI_REPO` nor `AJISAI_BIN`.
//
// It enforces the same `responseBytes` ceiling as the native backend. It used
// to enforce none: the native side got one for free from `execFile`'s
// `maxBuffer`, the worker handed envelopes back by structured clone with no
// size check at all, and the server declared the same limit for both. A limit
// only one backend applies is not a limit — it is a claim.

import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { Worker } from "node:worker_threads";
import { HostError } from "../host-error.js";

const here = dirname(fileURLToPath(import.meta.url));
const entryPath = join(here, "wasm-worker-entry.js");
const defaultWasmModulePath = join(here, "..", "wasm", "generated", "ajisai_core.js");

export class WasmWorkerBackend {
  static kind = "wasmWorker";

  constructor({ wallTimeMs, executionSteps, responseBytes, wasmModulePath = defaultWasmModulePath }) {
    this.wallTimeMs = wallTimeMs;
    this.executionSteps = executionSteps;
    this.responseBytes = responseBytes;
    this.wasmModulePath = wasmModulePath;
  }

  get kind() {
    return WasmWorkerBackend.kind;
  }

  /** Whether the packaged WASM bundle this backend needs is present. */
  static isAvailable(wasmModulePath = defaultWasmModulePath) {
    return existsSync(wasmModulePath);
  }

  #run(op, source, extra = {}) {
    return new Promise((resolve, reject) => {
      const worker = new Worker(entryPath, {
        workerData: {
          op,
          source,
          wasmModulePath: this.wasmModulePath,
          responseBytes: this.responseBytes,
          ...extra,
        },
      });
      let settled = false;
      const finish = (fn, value) => {
        if (settled) return;
        settled = true;
        clearTimeout(timer);
        worker.removeAllListeners();
        // `terminate()` resolves once the thread is actually gone. Not
        // awaiting it let a timed-out Worker keep running while the server
        // treated its execution slot as free.
        worker.terminate().finally(() => fn(value));
      };
      const timer = setTimeout(() => {
        finish(
          reject,
          new HostError("timeout", `Execution exceeded the ${this.wallTimeMs} ms wall-time limit.`),
        );
      }, this.wallTimeMs);
      worker.once("message", (message) => {
        if (message.error) {
          finish(reject, new HostError(message.error.code, message.error.message, {
            detail: message.error.detail,
          }));
        } else {
          finish(resolve, message.envelope);
        }
      });
      worker.once("error", (error) => {
        finish(
          reject,
          new HostError("backendFailure", "The Ajisai backend failed to produce a result.", {
            detail: `wasm worker: ${error.message}`,
          }),
        );
      });
      worker.once("exit", (code) => {
        // A crash the "error" event did not already report still leaves the
        // call unsettled; treat a non-zero exit with no message as a host
        // failure instead of leaving the caller to hang until the wall-time
        // timer fires.
        if (!settled && code !== 0) {
          finish(
            reject,
            new HostError("backendFailure", "The Ajisai backend failed to produce a result.", {
              detail: `wasm worker exited with code ${code}`,
            }),
          );
        }
      });
    });
  }

  compute(source) {
    return this.#run("compute", source, { stepLimit: this.executionSteps });
  }

  check(source) {
    return this.#run("check", source);
  }

  inferContracts(source) {
    return this.#run("inferContracts", source);
  }
}
