// Packaged WASM backend: runs the one-shot WASM agent entry point
// (`agent_compute` in `rust/src/wasm_interpreter_bindings/mod.rs`) inside a
// worker_threads Worker, in a fresh WebAssembly instance per call — the same
// one-shot-per-call isolation the native backend gets from spawning a
// subprocess per call (`wasm-worker-entry.js` says what is fresh and what is
// shared). Never runs WASM synchronously on the stdio server's main thread,
// and a Worker is terminated the moment the existing hard wall-time limit
// elapses.
//
// Self-contained: the WASM module ships inside the npm package
// (`wasm/generated/`, regenerated by `../../scripts/rebuild-mcp-wasm.sh`), so
// this backend needs neither `AJISAI_REPO` nor `AJISAI_BIN`.
//
// It enforces the same `responseBytes` ceiling as the native backend. It used
// to enforce none: the native side got one for free from `execFile`'s
// `maxBuffer`, the worker handed envelopes back by structured clone with no
// size check at all, and the server declared the same limit for both. A limit
// only one backend applies is not a limit — it is a claim.

import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { Worker } from "node:worker_threads";
import { HostError } from "../host-error.js";

const here = dirname(fileURLToPath(import.meta.url));
const entryPath = join(here, "wasm-worker-entry.js");
const defaultWasmModulePath = join(here, "..", "wasm", "generated", "ajisai_core.js");

export class WasmWorkerBackend {
  static kind = "wasmWorker";

  constructor({ wallTimeMs, executionSteps, responseBytes, wasmModulePath = defaultWasmModulePath }) {
    this.wallTimeMs = wallTimeMs;
    this.executionSteps = executionSteps;
    this.responseBytes = responseBytes;
    this.wasmModulePath = wasmModulePath;
  }

  get kind() {
    return WasmWorkerBackend.kind;
  }

  /** Whether the packaged WASM bundle this backend needs is present. */
  static isAvailable(wasmModulePath = defaultWasmModulePath) {
    return existsSync(wasmModulePath);
  }

  // Started Workers waiting for an operation, longest-waiting first.
  // Starting a Worker is most of what a call used to cost (50-100 ms, against
  // ~0.3 ms for `1 2 ADD` itself), and calls in quick succession found the one
  // spare Worker still starting. A Worker that answered is kept: it has already
  // prepared a fresh instance for its next operation, so reusing it changes
  // nothing a call can observe. One that timed out, crashed or exited is never
  // reused. The pool holds at most `#maxIdle` Workers; at least one is always
  // started ahead of the next call.
  #idle = [];
  static #maxIdle = 4;

  #spawn() {
    return new Worker(entryPath, {
      workerData: { wasmModulePath: this.wasmModulePath },
    });
  }

  // An idle Worker must neither keep the process alive nor bring it down: a
  // failure surfaces on the call that takes it (the `exit` / `error` handlers
  // in `#run`), and one that died while idle leaves the pool.
  #park(worker) {
    worker.unref();
    const onIdleFailure = () => {
      const index = this.#idle.indexOf(worker);
      if (index >= 0) this.#idle.splice(index, 1);
    };
    worker.on("error", onIdleFailure);
    worker.on("exit", onIdleFailure);
    this.#idle.push(worker);
  }

  // The Worker that has waited longest is the one most likely to have
  // finished preparing its next instance.
  #take() {
    const worker = this.#idle.shift() ?? this.#spawn();
    worker.removeAllListeners();
    worker.ref();
    if (this.#idle.length === 0) this.#park(this.#spawn());
    return worker;
  }

  // A Worker that answered goes back to the pool, unless the pool is full.
  #release(worker) {
    worker.removeAllListeners();
    if (this.#idle.length >= WasmWorkerBackend.#maxIdle) {
      worker.terminate();
      return;
    }
    this.#park(worker);
  }

  #run(op, source, extra = {}) {
    return new Promise((resolve, reject) => {
      const worker = this.#take();
      worker.postMessage({ op, source, responseBytes: this.responseBytes, ...extra });
      let settled = false;
      const finish = (fn, value, answered = false) => {
        if (settled) return;
        settled = true;
        clearTimeout(timer);
        // A Worker that posted an answer, success or reported failure, has
        // finished its operation and is ready for another. Every other
        // outcome (timeout, crash, exit) tears it down, and waits until the
        // thread is actually gone: not waiting let a timed-out Worker keep
        // running while the server treated its execution slot as free.
        if (answered) {
          this.#release(worker);
          fn(value);
        } else {
          worker.removeAllListeners();
          worker.terminate().finally(() => fn(value));
        }
      };
      const timer = setTimeout(() => {
        finish(
          reject,
          new HostError("timeout", `Execution exceeded the ${this.wallTimeMs} ms wall-time limit.`),
        );
      }, this.wallTimeMs);
      worker.once("message", (message) => {
        if (message.error) {
          finish(reject, new HostError(message.error.code, message.error.message, {
            detail: message.error.detail,
          }), true);
        } else {
          finish(resolve, message.envelope, true);
        }
      });
      worker.once("error", (error) => {
        finish(
          reject,
          new HostError("backendFailure", "The Ajisai backend failed to produce a result.", {
            detail: `wasm worker: ${error.message}`,
          }),
        );
      });
      worker.once("exit", (code) => {
        // A crash the "error" event did not already report still leaves the
        // call unsettled; treat a non-zero exit with no message as a host
        // failure instead of leaving the caller to hang until the wall-time
        // timer fires.
        if (!settled && code !== 0) {
          finish(
            reject,
            new HostError("backendFailure", "The Ajisai backend failed to produce a result.", {
              detail: `wasm worker exited with code ${code}`,
            }),
          );
        }
      });
    });
  }

  compute(source) {
    return this.#run("compute", source, { stepLimit: this.executionSteps });
  }

  check(source) {
    return this.#run("check", source);
  }

  inferContracts(source) {
    return this.#run("inferContracts", source);
  }

  outcomes(source) {
    return this.#run("outcomes", source, { stepLimit: this.executionSteps });
  }
}
