/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_ajisaiinterpreter_free: (a: number, b: number) => void;
export const ajisaiinterpreter_clear_io_output_buffer: (a: number) => void;
export const ajisaiinterpreter_execute: (a: number, b: number, c: number) => any;
export const ajisaiinterpreter_execute_step: (a: number, b: number, c: number) => any;
export const ajisaiinterpreter_get_builtin_words_info: (a: number) => any;
export const ajisaiinterpreter_get_custom_words_info: (a: number) => any;
export const ajisaiinterpreter_get_io_output_buffer: (a: number) => [number, number];
export const ajisaiinterpreter_get_stack: (a: number) => any;
export const ajisaiinterpreter_get_word_definition: (a: number, b: number, c: number) => any;
export const ajisaiinterpreter_new: () => number;
export const ajisaiinterpreter_remove_word: (a: number, b: number, c: number) => void;
export const ajisaiinterpreter_reset: (a: number) => any;
export const ajisaiinterpreter_restore_custom_words: (a: number, b: any) => [number, number];
export const ajisaiinterpreter_restore_stack: (a: number, b: any) => [number, number];
export const ajisaiinterpreter_set_input_buffer: (a: number, b: number, c: number) => void;
export const wasm_bindgen__closure__destroy__h24a835206c79cbdb: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hd890e298e6ea50a4: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h96dea7eb0a3eb991: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h7e4813122c96a2ed: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h77bea7aa827dfb48: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
