// @generated by scripts/generate-core-word-docs.mjs; do not edit.

pub(crate) struct GeneratedCoreWordDoc {
    pub(crate) name: &'static str,
    pub(crate) hover_summary: &'static str,
    pub(crate) hover_syntax: &'static str,
}

pub(crate) const GENERATED_CORE_WORD_DOCS: &[GeneratedCoreWordDoc] = &[
    GeneratedCoreWordDoc {
        name: "EAT",
        hover_summary: "EAT — consume operands",
        hover_syntax: ", +",
    },
    GeneratedCoreWordDoc {
        name: "KEEP",
        hover_summary: "KEEP — keep operands and append result",
        hover_syntax: ",, +",
    },
    GeneratedCoreWordDoc {
        name: "GET",
        hover_summary: "GET — extract element at index",
        hover_syntax: "[ 10 20 30 ] [ 0 ] GET",
    },
    GeneratedCoreWordDoc {
        name: "INSERT",
        hover_summary: "INSERT — insert element at index",
        hover_syntax: "[ 1 3 ] [ 1 2 ] INSERT",
    },
    GeneratedCoreWordDoc {
        name: "REPLACE",
        hover_summary: "REPLACE — replace element at index",
        hover_syntax: "[ 1 2 3 ] [ 0 9 ] REPLACE",
    },
    GeneratedCoreWordDoc {
        name: "REMOVE",
        hover_summary: "REMOVE — remove element at index",
        hover_syntax: "[ 1 2 3 ] [ 0 ] REMOVE",
    },
    GeneratedCoreWordDoc {
        name: "LENGTH",
        hover_summary: "LENGTH — return element count",
        hover_syntax: "[ 1 2 3 ] LENGTH",
    },
    GeneratedCoreWordDoc {
        name: "TAKE",
        hover_summary: "TAKE — take N elements from start or end",
        hover_syntax: "[ 1 2 3 4 5 ] [ 3 ] TAKE",
    },
    GeneratedCoreWordDoc {
        name: "SPLIT",
        hover_summary: "SPLIT — split vector at sizes",
        hover_syntax: "[ 1 2 3 4 ] [ 2 2 ] SPLIT",
    },
    GeneratedCoreWordDoc {
        name: "CONCAT",
        hover_summary: "CONCAT — flatten and concatenate vectors",
        hover_syntax: "[ 1 2 ] [ 3 4 ] CONCAT",
    },
    GeneratedCoreWordDoc {
        name: "REVERSE",
        hover_summary: "REVERSE — reverse element order",
        hover_syntax: "[ 1 2 3 ] REVERSE",
    },
    GeneratedCoreWordDoc {
        name: "RANGE",
        hover_summary: "RANGE — generate numeric sequence",
        hover_syntax: "[ 0 5 ] RANGE",
    },
    GeneratedCoreWordDoc {
        name: "REORDER",
        hover_summary: "REORDER — reorder by index list",
        hover_syntax: "[ 'a' 'b' 'c' ] [ 2 0 1 ] REORDER",
    },
    GeneratedCoreWordDoc {
        name: "COLLECT",
        hover_summary: "COLLECT — collect N items into vector",
        hover_syntax: "1 2 3 3 COLLECT",
    },
    GeneratedCoreWordDoc {
        name: "TRUE",
        hover_summary: "TRUE — push TRUE",
        hover_syntax: "TRUE",
    },
    GeneratedCoreWordDoc {
        name: "FALSE",
        hover_summary: "FALSE — push FALSE",
        hover_syntax: "FALSE",
    },
    GeneratedCoreWordDoc {
        name: "NIL",
        hover_summary: "NIL — push NIL",
        hover_syntax: "NIL",
    },
    GeneratedCoreWordDoc {
        name: "NIL?",
        hover_summary: "NIL? — test whether a value is absent",
        hover_syntax: "1 0 / NIL?",
    },
    GeneratedCoreWordDoc {
        name: "NIL-REASON",
        hover_summary: "NIL-REASON — read the NIL reason protocol string",
        hover_syntax: "1 0 / NIL-REASON",
    },
    GeneratedCoreWordDoc {
        name: "CHARS",
        hover_summary: "CHARS — split string into characters",
        hover_syntax: "'hi' CHARS",
    },
    GeneratedCoreWordDoc {
        name: "JOIN",
        hover_summary: "JOIN — join characters into string",
        hover_syntax: "[ 'h' 'i' ] JOIN",
    },
    GeneratedCoreWordDoc {
        name: "TRIM",
        hover_summary: "TRIM — strip leading and trailing whitespace",
        hover_syntax: "'  hi  ' TRIM",
    },
    GeneratedCoreWordDoc {
        name: "TOKENIZE",
        hover_summary: "TOKENIZE — split string by separator",
        hover_syntax: "'a,b,c' ',' TOKENIZE",
    },
    GeneratedCoreWordDoc {
        name: "SUBSTITUTE",
        hover_summary: "SUBSTITUTE — replace substring occurrences",
        hover_syntax: "'hello' 'l' 'L' SUBSTITUTE",
    },
    GeneratedCoreWordDoc {
        name: "STARTS-WITH?",
        hover_summary: "STARTS-WITH? — prefix predicate",
        hover_syntax: "'hello' 'he' STARTS-WITH?",
    },
    GeneratedCoreWordDoc {
        name: "ENDS-WITH?",
        hover_summary: "ENDS-WITH? — suffix predicate",
        hover_syntax: "'hello' 'lo' ENDS-WITH?",
    },
    GeneratedCoreWordDoc {
        name: "NUM",
        hover_summary: "NUM — parse to number",
        hover_syntax: "'42' NUM",
    },
    GeneratedCoreWordDoc {
        name: "STR",
        hover_summary: "STR — convert to string",
        hover_syntax: "42 STR",
    },
    GeneratedCoreWordDoc {
        name: "CHR",
        hover_summary: "CHR — make a character",
        hover_syntax: "65 CHR",
    },
    GeneratedCoreWordDoc {
        name: "ADD",
        hover_summary: "ADD — add values",
        hover_syntax: "1 2 +",
    },
    GeneratedCoreWordDoc {
        name: "SUB",
        hover_summary: "SUB — subtract values",
        hover_syntax: "5 3 -",
    },
    GeneratedCoreWordDoc {
        name: "MUL",
        hover_summary: "MUL — multiply values",
        hover_syntax: "2 4 *",
    },
    GeneratedCoreWordDoc {
        name: "DIV",
        hover_summary: "DIV — divide values",
        hover_syntax: "10 2 /",
    },
    GeneratedCoreWordDoc {
        name: "EQ",
        hover_summary: "EQ — test equality",
        hover_syntax: "1 1 =",
    },
    GeneratedCoreWordDoc {
        name: "LT",
        hover_summary: "LT — test less than",
        hover_syntax: "1 2 <",
    },
    GeneratedCoreWordDoc {
        name: "LTE",
        hover_summary: "LTE — test less than or equal",
        hover_syntax: "1 1 <=",
    },
    GeneratedCoreWordDoc {
        name: "GT",
        hover_summary: "GT — test greater than",
        hover_syntax: "2 1 >",
    },
    GeneratedCoreWordDoc {
        name: "GTE",
        hover_summary: "GTE — test greater than or equal",
        hover_syntax: "1 1 >=",
    },
    GeneratedCoreWordDoc {
        name: "NEQ",
        hover_summary: "NEQ — test inequality",
        hover_syntax: "1 2 <>",
    },
    GeneratedCoreWordDoc {
        name: "AND",
        hover_summary: "AND — logical AND",
        hover_syntax: "TRUE TRUE &",
    },
    GeneratedCoreWordDoc {
        name: "OR",
        hover_summary: "OR — logical OR",
        hover_syntax: "TRUE FALSE OR",
    },
    GeneratedCoreWordDoc {
        name: "NOT",
        hover_summary: "NOT — logical negation",
        hover_syntax: "TRUE NOT",
    },
    GeneratedCoreWordDoc {
        name: "COND",
        hover_summary: "COND — evaluate guard/body clauses",
        hover_syntax: "1 { TRUE } { 'y' } { IDLE } { 'n' } COND",
    },
    GeneratedCoreWordDoc {
        name: "VENT",
        hover_summary: "VENT — lazy NIL-coalescing fallback",
        hover_syntax: "NIL ^ [ 0 ]",
    },
    GeneratedCoreWordDoc {
        name: "MAP",
        hover_summary: "MAP — apply block to each element",
        hover_syntax: "[ 1 2 3 ] { [ 2 ] * } MAP",
    },
    GeneratedCoreWordDoc {
        name: "FILTER",
        hover_summary: "FILTER — keep elements matching predicate",
        hover_syntax: "[ 1 2 3 ] { [ 2 ] = } FILTER",
    },
    GeneratedCoreWordDoc {
        name: "FOLD",
        hover_summary: "FOLD — reduce with initial value",
        hover_syntax: "[ 1 2 3 ] [ 0 ] { + } FOLD",
    },
    GeneratedCoreWordDoc {
        name: "ANY",
        hover_summary: "ANY — true if any element matches",
        hover_syntax: "[ 1 2 3 ] { [ 2 ] = } ANY",
    },
    GeneratedCoreWordDoc {
        name: "ALL",
        hover_summary: "ALL — true if all elements match",
        hover_syntax: "[ 2 4 ] { [ 2 ] MOD [ 0 ] = } ALL",
    },
    GeneratedCoreWordDoc {
        name: "PRINT",
        hover_summary: "PRINT — output value to display",
        hover_syntax: "42 PRINT",
    },
    GeneratedCoreWordDoc {
        name: "DEF",
        hover_summary: "DEF — define user word",
        hover_syntax: "{ 2 * } 'DOUBLE' DEF",
    },
    GeneratedCoreWordDoc {
        name: "DEL",
        hover_summary: "DEL — delete user word",
        hover_syntax: "{ [ 1 ] } 'W' DEF 'W' DEL",
    },
    GeneratedCoreWordDoc {
        name: "LOOKUP",
        hover_summary: "LOOKUP — show word documentation",
        hover_syntax: "'ADD' ?",
    },
    GeneratedCoreWordDoc {
        name: "FILL",
        hover_summary: "FILL — fill shape with value",
        hover_syntax: "[ 2 2 0 ] FILL",
    },
    GeneratedCoreWordDoc {
        name: "MOD",
        hover_summary: "MOD — modulo",
        hover_syntax: "7 3 %",
    },
    GeneratedCoreWordDoc {
        name: "FLOOR",
        hover_summary: "FLOOR — round toward negative infinity",
        hover_syntax: "[ 7/3 ] FLOOR",
    },
    GeneratedCoreWordDoc {
        name: "CEIL",
        hover_summary: "CEIL — round toward positive infinity",
        hover_syntax: "[ 7/3 ] CEIL",
    },
    GeneratedCoreWordDoc {
        name: "ROUND",
        hover_summary: "ROUND — round to nearest integer",
        hover_syntax: "[ 5/2 ] ROUND",
    },
    GeneratedCoreWordDoc {
        name: "EXEC",
        hover_summary: "EXEC — execute vector as code",
        hover_syntax: "[ 1 2 + ] EXEC",
    },
    GeneratedCoreWordDoc {
        name: "SQRT",
        hover_summary: "SQRT — exact square root",
        hover_syntax: "2 SQRT",
    },
    GeneratedCoreWordDoc {
        name: "ABS",
        hover_summary: "Absolute value of a number.",
        hover_syntax: "-2 ABS",
    },
    GeneratedCoreWordDoc {
        name: "NEG",
        hover_summary: "Numeric negation.",
        hover_syntax: "2 NEG",
    },
    GeneratedCoreWordDoc {
        name: "SIGN",
        hover_summary: "Sign of a number: -1, 0, or 1.",
        hover_syntax: "-2 SIGN",
    },
    GeneratedCoreWordDoc {
        name: "MIN",
        hover_summary: "Smaller of two numbers.",
        hover_syntax: "1 2 MIN",
    },
    GeneratedCoreWordDoc {
        name: "MAX",
        hover_summary: "Larger of two numbers.",
        hover_syntax: "1 2 MAX",
    },
    GeneratedCoreWordDoc {
        name: "SORT",
        hover_summary: "Return a copy of a vector sorted in ascending order.",
        hover_syntax: "[ 3 1 2 ] SORT",
    },
    GeneratedCoreWordDoc {
        name: "UNIQUE",
        hover_summary: "UNIQUE — remove duplicates, keeping first-occurrence order",
        hover_syntax: "[ 1 2 1 ] UNIQUE",
    },
    GeneratedCoreWordDoc {
        name: "CONTAINS",
        hover_summary: "True if a vector contains an element equal to the given value.",
        hover_syntax: "[ 1 2 ] 2 CONTAINS",
    },
    GeneratedCoreWordDoc {
        name: "INDEX-OF",
        hover_summary: "Index of the first element equal to the value; Bubble/NIL if absent.",
        hover_syntax: "[ 1 2 ] 2 INDEX-OF",
    },
];
