"""Exact-real scalar arithmetic for the Python port of Ajisai.

This module is written from SPECIFICATION.html alone (Section 4.2). The spec
models every numeric value as an exact real, internally a (possibly lazy)
continued fraction. The admitted domain produced by the current Coreword set is
the rationals plus square roots of rationals (MATH@SQRT), which all live in a
field generated by square roots of square-free integers.

We therefore represent a scalar as an ``AlgebraicReal``: a finite Q-linear
combination of distinct square-free surds ``sqrt(d)`` (with ``d = 1`` denoting
the rational part). This representation is:

  * closed under +, -, * (Section 7.3);
  * exact for equality and ordering of the admitted domain (Section 2.3.1: "In
    the current algebraic domain, L1 comparisons are total and exact"), because
    the surds ``sqrt(d)`` of distinct square-free ``d`` are linearly independent
    over Q;
  * expandable as a nearest-integer continued fraction (NICF, Section 4.2.5) so
    COMPARE-WITHIN (Section 7.4.2) can honour an explicit partial-quotient
    budget and yield UNKNOWN.

Division is total over the whole domain: a single-surd divisor is rationalised
directly, and a multi-surd divisor is rationalised through the field's Galois
conjugates (Section 4.2.7). ``DomainLimitation`` is therefore reserved for
pathological radicand complexity (an implementation resource limit), not for any
value the current Coreword set can construct.
"""

from __future__ import annotations

from fractions import Fraction
from math import isqrt
from typing import Dict, Iterator, Optional, Tuple


class DomainLimitation(Exception):
    """Raised when an operation leaves the implemented exact-real sub-domain."""


def _squarefree(n: int) -> Tuple[int, int]:
    """Factor n = s*s * d with d square-free, n >= 0. Returns (s, d)."""
    if n < 0:
        raise ValueError("squarefree of negative")
    if n == 0:
        return (0, 1)
    s = 1
    d = n
    f = 2
    while f * f <= d:
        while d % (f * f) == 0:
            d //= f * f
            s *= f
        f += 1 if f == 2 else 2
    return (s, d)


def _prime_factors(d: int) -> Tuple[int, ...]:
    """Distinct prime factors of a square-free positive integer d (d >= 1)."""
    out = []
    m = d
    f = 2
    while f * f <= m:
        if m % f == 0:
            out.append(f)
            m //= f
        else:
            f += 1 if f == 2 else 2
    if m > 1:
        out.append(m)
    return tuple(out)


# Guard against pathological blow-up in general reciprocation (2**k conjugates).
_MAX_RADICAND_PRIMES = 10


class AlgebraicReal:
    """A finite Q-combination of distinct square-free surds.

    Stored as a dict ``{d: Fraction}`` where ``d`` is a square-free positive
    integer (``d == 1`` is the rational part) and the coefficient is non-zero.
    The empty dict is the value 0.
    """

    __slots__ = ("terms",)

    def __init__(self, terms: Optional[Dict[int, Fraction]] = None):
        cleaned: Dict[int, Fraction] = {}
        if terms:
            for d, c in terms.items():
                c = Fraction(c)
                if c != 0:
                    cleaned[d] = c
        self.terms = cleaned

    # -- constructors -----------------------------------------------------
    @staticmethod
    def from_rational(value) -> "AlgebraicReal":
        f = Fraction(value)
        return AlgebraicReal({1: f} if f != 0 else {})

    @staticmethod
    def sqrt_of(value: "AlgebraicReal") -> "AlgebraicReal":
        """sqrt of a non-negative rational (Section 7.3, MATH@SQRT)."""
        if not value.is_rational():
            raise DomainLimitation("SQRT of a non-rational is outside the port domain")
        r = value.rational_value()
        if r < 0:
            raise ValueError("SQRT of negative")
        if r == 0:
            return AlgebraicReal()
        # sqrt(p/q) = sqrt(p*q)/q
        p, q = r.numerator, r.denominator
        s, d = _squarefree(p * q)
        coeff = Fraction(s, q)
        if d == 1:
            return AlgebraicReal({1: coeff})
        return AlgebraicReal({d: coeff})

    # -- predicates -------------------------------------------------------
    def is_zero(self) -> bool:
        return not self.terms

    def is_rational(self) -> bool:
        return all(d == 1 for d in self.terms)

    def is_integer(self) -> bool:
        return self.is_rational() and self.rational_value().denominator == 1

    def rational_value(self) -> Fraction:
        if not self.is_rational():
            raise ValueError("not rational")
        return self.terms.get(1, Fraction(0))

    def single_surd(self) -> Optional[Tuple[Fraction, Fraction, int]]:
        """If value is a + b*sqrt(d) with one surd, return (a, b, d)."""
        surds = [d for d in self.terms if d != 1]
        if len(surds) > 1:
            return None
        a = self.terms.get(1, Fraction(0))
        if not surds:
            return (a, Fraction(0), 1)
        d = surds[0]
        return (a, self.terms[d], d)

    # -- arithmetic -------------------------------------------------------
    def __add__(self, other: "AlgebraicReal") -> "AlgebraicReal":
        out = dict(self.terms)
        for d, c in other.terms.items():
            out[d] = out.get(d, Fraction(0)) + c
        return AlgebraicReal(out)

    def __neg__(self) -> "AlgebraicReal":
        return AlgebraicReal({d: -c for d, c in self.terms.items()})

    def __sub__(self, other: "AlgebraicReal") -> "AlgebraicReal":
        return self + (-other)

    def __mul__(self, other: "AlgebraicReal") -> "AlgebraicReal":
        out: Dict[int, Fraction] = {}
        for di, ci in self.terms.items():
            for dj, cj in other.terms.items():
                s, d = _squarefree(di * dj)
                out[d] = out.get(d, Fraction(0)) + ci * cj * s
        return AlgebraicReal(out)

    def reciprocal(self) -> "AlgebraicReal":
        """Multiplicative inverse within the multiquadratic field (Section 4.2.7).

        The admitted domain D is a field, so 1/x exists for every non-zero x.
        For a single surd we rationalise the denominator directly; for several
        distinct surds we multiply by all non-trivial Galois conjugates (sign
        flips of each prime radical) so the product with x is a rational norm.
        """
        if self.is_zero():
            raise ZeroDivisionError("reciprocal of zero")
        sd = self.single_surd()
        if sd is not None:
            a, b, d = sd
            if b == 0:
                return AlgebraicReal({1: 1 / a})
            # 1/(a + b*sqrt(d)) = (a - b*sqrt(d)) / (a^2 - b^2 d)
            denom = a * a - b * b * d
            out: Dict[int, Fraction] = {}
            if a != 0:
                out[1] = a / denom
            out[d] = -b / denom
            return AlgebraicReal(out)
        # General multiquadratic case: rationalise via the automorphism group.
        primes = sorted({p for d in self.terms if d != 1
                         for p in _prime_factors(d)})
        if len(primes) > _MAX_RADICAND_PRIMES:
            raise DomainLimitation("reciprocal radicand complexity exceeds limit")
        numerator = AlgebraicReal.from_rational(1)
        # every sign assignment except the identity (all +1)
        for mask in range(1, 1 << len(primes)):
            flip = {p: (-1 if (mask >> i) & 1 else 1) for i, p in enumerate(primes)}
            numerator = numerator * self._conjugate(flip)
        norm = (self * numerator)
        if not norm.is_rational():  # invariant: the field norm is rational
            raise DomainLimitation("reciprocal norm is not rational")
        return numerator * AlgebraicReal({1: 1 / norm.rational_value()})

    def _conjugate(self, flip: Dict[int, int]) -> "AlgebraicReal":
        out: Dict[int, Fraction] = {}
        for d, c in self.terms.items():
            sign = 1
            if d != 1:
                for p in _prime_factors(d):
                    sign *= flip.get(p, 1)
            out[d] = c * sign
        return AlgebraicReal(out)

    def __truediv__(self, other: "AlgebraicReal") -> "AlgebraicReal":
        return self * other.reciprocal()

    # -- ordering ---------------------------------------------------------
    def sign(self) -> int:
        """Exact sign (-1, 0, 1). Total over the implemented domain."""
        if self.is_zero():
            return 0
        if self.is_rational():
            r = self.rational_value()
            return 1 if r > 0 else -1
        sd = self.single_surd()
        if sd is not None:
            a, b, d = sd
            # sign of a + b*sqrt(d), with sqrt(d) > 0
            if a == 0:
                return 1 if b > 0 else -1
            if b == 0:
                return 1 if a > 0 else -1
            if a > 0 and b > 0:
                return 1
            if a < 0 and b < 0:
                return -1
            # opposite signs: compare a^2 with b^2 d (cannot be equal: sqrt(d) irrational)
            lhs = a * a
            rhs = b * b * d
            if a > 0:  # b < 0: positive iff a^2 > b^2 d
                return 1 if lhs > rhs else -1
            else:  # a < 0, b > 0: positive iff b^2 d > a^2
                return 1 if rhs > lhs else -1
        # multi-surd: nonzero by linear independence; resolve by interval refinement
        eps = Fraction(1)
        while True:
            lo, hi = self.interval(eps)
            if lo > 0:
                return 1
            if hi < 0:
                return -1
            eps /= 16

    def compare(self, other: "AlgebraicReal") -> int:
        """Exact three-way comparison (Section 7.4, current algebraic domain)."""
        return (self - other).sign()

    def __eq__(self, other) -> bool:  # structural == exact value equality
        if not isinstance(other, AlgebraicReal):
            return NotImplemented
        return self.terms == other.terms

    def __hash__(self):
        return hash(tuple(sorted((d, c) for d, c in self.terms.items())))

    # -- numeric bounds & integer parts ----------------------------------
    def interval(self, eps: Fraction) -> Tuple[Fraction, Fraction]:
        """Rational [lo, hi] enclosing the value with hi-lo < eps."""
        lo = Fraction(0)
        hi = Fraction(0)
        for d, c in self.terms.items():
            if d == 1:
                lo += c
                hi += c
                continue
            slo, shi = _sqrt_bounds(d, eps)
            if c >= 0:
                lo += c * slo
                hi += c * shi
            else:
                lo += c * shi
                hi += c * slo
        return (lo, hi)

    def floor(self) -> int:
        if self.is_rational():
            r = self.rational_value()
            return r.numerator // r.denominator
        eps = Fraction(1, 4)
        while True:
            lo, hi = self.interval(eps)
            flo = lo.numerator // lo.denominator
            fhi = hi.numerator // hi.denominator
            if flo == fhi:
                return flo
            eps /= 16

    def ceil(self) -> int:
        f = self.floor()
        # exact integer?
        if self.is_integer():
            return self.rational_value().numerator
        return f + 1

    def round_half_away(self) -> int:
        """ROUND: nearest integer, ties (exactly .5) away from zero."""
        if self.is_rational():
            r = self.rational_value()
            f = r.numerator // r.denominator  # floor
            frac = r - f
            if frac < Fraction(1, 2):
                return f
            if frac > Fraction(1, 2):
                return f + 1
            # tie: away from zero
            return f + 1 if r > 0 else f  # r>0 -> up; r<0 -> toward zero is f
        # irrational: never an exact half; refine
        f = self.floor()
        frac = self - AlgebraicReal.from_rational(f)
        # frac in (0,1); compare with 1/2
        c = (frac - AlgebraicReal.from_rational(Fraction(1, 2))).sign()
        return f if c < 0 else f + 1

    def round_nearest_half_down(self) -> int:
        """NICF digit: nearest integer, exact half rounds down (Section 4.2.5)."""
        if self.is_rational():
            r = self.rational_value()
            # b = ceil((2num - den) / (2 den))
            num = r.numerator
            den = r.denominator
            x = 2 * num - den
            y = 2 * den
            # ceiling division
            return -((-x) // y)
        f = self.floor()
        frac = self - AlgebraicReal.from_rational(f)
        c = (frac - AlgebraicReal.from_rational(Fraction(1, 2))).sign()
        # irrational, c != 0
        return f if c < 0 else f + 1

    # -- continued fractions ---------------------------------------------
    def rcf_terms(self, limit: int = 64) -> Iterator[int]:
        """Regular continued fraction partial quotients (Section 4.2.1)."""
        x = self
        for _ in range(limit):
            a = x.floor()
            yield a
            rem = x - AlgebraicReal.from_rational(a)
            if rem.is_zero():
                return
            x = rem.reciprocal()

    def nicf_terms(self, limit: int = 64) -> Iterator[int]:
        """Nearest-integer continued fraction terms (Section 4.2.5)."""
        x = self
        for _ in range(limit):
            b = x.round_nearest_half_down()
            yield b
            rem = x - AlgebraicReal.from_rational(b)
            if rem.is_zero():
                return
            x = rem.reciprocal()

    # -- display ----------------------------------------------------------
    def __repr__(self) -> str:
        return f"AlgebraicReal({self.terms!r})"


_SQRT_CACHE: Dict[Tuple[int, int], Tuple[Fraction, Fraction]] = {}


def _sqrt_bounds(d: int, eps: Fraction) -> Tuple[Fraction, Fraction]:
    """Rational lower/upper bounds for sqrt(d) with width < eps."""
    # choose denominator D so that 1/D < eps
    D = 1
    while Fraction(1, D) >= eps:
        D *= 2
    lo_num = isqrt(d * D * D)
    lo = Fraction(lo_num, D)
    hi = Fraction(lo_num + 1, D)
    return (lo, hi)
