name: Build and Deploy Ajisai

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install wasm-pack
      run: |
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    
    - name: Build WASM
      run: |
        cd rust
        wasm-pack build --target web --out-dir ../js/pkg
        
        # wasm-packが生成する.gitignoreを削除
        rm -f ../js/pkg/.gitignore
        
        # 生成されたファイルを確認
        echo "=== Generated files in js/pkg ==="
        ls -la ../js/pkg/
        
        # JSファイルの内容を確認（最初の数行）
        echo ""
        echo "=== First lines of generated JS files ==="
        head -n 5 ../js/pkg/*.js || true
    
    - name: List generated files
      run: |
        echo "=== js/pkg contents ==="
        ls -la js/pkg/ || echo "pkg directory not found"
        echo ""
        echo "=== All .wasm files ==="
        find . -name "*.wasm" -type f
    
    - name: Create .nojekyll
      run: touch .nojekyll
    
    - name: Commit and push generated files
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f js/pkg
        git add .nojekyll
        git diff --staged --quiet || git commit -m "Add WASM build artifacts"
        git push origin main || echo "No changes to push"
