name: Build and Deploy Ajisai

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: true
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install wasm-pack
      run: |
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    
    - name: Build WASM
      run: |
        cd rust
        wasm-pack build --target web --out-dir ../js/pkg
        
        # 生成されたファイルを確認
        echo "=== Generated files in js/pkg ==="
        ls -la ../js/pkg/
    
    - name: Create .nojekyll
      run: touch .nojekyll
    
    - name: Configure Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    
    - name: Check and commit files
      run: |
        # 現在の状態を確認
        echo "=== Git status before ==="
        git status
        
        # pkgフォルダを強制的に追加
        git add -f js/pkg/
        git add .nojekyll
        
        # 変更があるか確認
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          echo "=== Files to be committed ==="
          git diff --staged --name-only
          
          # コミット
          git commit -m "Add WASM build artifacts [skip ci]"
          
          # ★★★ ここを修正 ★★★
          # pushする前にリモートの変更を取り込む
          # コンフリクトを避けるためrebase戦略を使用
          git pull --rebase origin main
          
          # プッシュ
          git push origin main
        fi
