name: Test Ajisai

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rust/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        working-directory: rust
        run: |
          # rlibクレートタイプでテストを実行
          cargo test --lib --verbose
          
      - name: Verify WASM build
        working-directory: rust
        run: |
          # WASMビルドが成功するかテスト
          rustup target add wasm32-unknown-unknown
          cargo check --target wasm32-unknown-unknown
